jirasec: {
    JIRA_USERNAME:'rosegpeterson@gmail.com',
    JIRA_TOKEN:'HRsrB1KCDQD5m7hvmVcw6F33'
}

rpl: {
    JIRA_PROJECT_KEY: "RPP",
    JIRA_PROJECT: "RPPPRJ",
    JIRA_SPRINT: "Sprint 1",
    JIRA_SPRINT_KEY: "Sprint1",
    SPRINT_START_DATE:"2021-08-10",
    SPRINT_END_DATE:"2021-08-24",
}

rppproj: {
    JIRA_PROJECT_KEY: "RPL",
    JIRA_PROJECT: "RPL1",
    JIRA_SPRINT: "Sprint 1",
    JIRA_SPRINT_KEY: "Sprint1",
    SPRINT_START_DATE:"2021-08-17",
    SPRINT_END_DATE:"2021-08-31",
}

params:
    JIRA_URL: 'https://summusappgroup.atlassian.net'
    JIRA_API: '/rest/api/2/'


