jirasec: {
    JIRA_USERNAME:'rosegpeterson@gmail.com',
    JIRA_TOKEN:'HRsrB1KCDQD5m7hvmVcw6F33'
}

csmproj: {
    JIRA_PROJECT_KEY: "CADITSM",
    JIRA_PROJECT: "Cadalys - Service Management",
    JIRA_SPRINT: "Sprint 24 - Raleigh",
    JIRA_SPRINT_KEY: "Sprint24",
    SPRINT_START_DATE:"2021-08-10",
    SPRINT_END_DATE:"2021-08-24",
}

conciergeproj: {
    JIRA_PROJECT_KEY: "CADALYSCNG",
    JIRA_PROJECT: "Cadalys - Concierge",
    JIRA_SPRINT: "Sprint 11 - Paris",
    JIRA_SPRINT_KEY: "Sprint11",
    SPRINT_START_DATE:"2021-08-17",
    SPRINT_END_DATE:"2021-08-31",
}

params:
    JIRA_URL: 'https://summusappgroup.atlassian.net'
    JIRA_API: '/rest/api/2/'


